jms_serializer:
  visitors:
    xml_serialization:
      format_output: '%kernel.debug%'
  default_context:
    serialization:
      serialize_null: true
  metadata:
    auto_detection: true
    directories:
      AppEntity:
        namespace_prefix: "App\\Entity"
        path: "%kernel.project_dir%/config/serializer"