framework:
  validation:
    email_validation_mode: html5
    enabled: true
    enable_annotations: false
    mapping:
      paths:
        - "%kernel.project_dir%/config/validator"

    # Enables validator auto-mapping support.
    # For instance, basic validation constraints will be inferred from Doctrine's metadata.
    #auto_mapping:
    #    App\Entity\: []
